### PR TITLE
Update orientation Hook

### PR DESCRIPTION
**Pull request by ChRen95**
Update the orientation hook in RollPass to also accept strings, therefore one could just pass `vertical`, `horizontal`, `Y` or `AntiY`. This would be more convenient for the human eye.

### CODE REVIEW

**Comment by axtimhaus** [comment]
Good idea, but there is only the type of the hook updated. No implementation for this logic?

**Comment by ChRen95** [comment]
Just saw that core handles rotating therefore will need to implement the logic.

**Comment by ChRen95** [comment]
Ready for merging

**Review by axtimhaus — APPROVED** [review]

**Comment by axtimhaus** [comment]
Should we consider to make Y configuration the default for 3-roll-passes?

**Comment by ChRen95** [comment]
Yes, let's make Y our default.

**Pull request merged**
